service: contract-testing-consumer

frameworkVersion: "2"

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

useDotenv: true

custom:
  serverless-offline:
    httpPort: 4000
  stages:
    - dev
    - staging
    - prod
  webpack:
    packager: yarn
    webpackConfig: ./webpack.config.js

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-north-1
  runtime: nodejs12.x
  stackName: ${self:service}
  lambdaHashingVersion: 20201221
  environment:
    LOG_LEVEL: ${env:LOG_LEVEL}

functions:
  personConsumer:
    handler: src/functions/personConsumer.handler
    name: ${self:service}-${self:provider.stage}-personConsumer
    events:
      - sns: ${self:service}-${self:provider.stage}-personTopic
