name: can-i-deploy-action

inputs:
  PACT_BROKER_BASE_URL:
    description: "Pact broker url"
    required: true
  PACT_BROKER_TOKEN:
    description: "Pact broker token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup pact-cli
      run: docker pull pactfoundation/pact-cli:latest
      shell: bash
    - name: Can I deploy?
      run: >
        docker run pactfoundation/pact-cli:latest
        broker can-i-deploy
        --pacticipant $PACTICIPANT 
        --version ${{ github.sha }}
        --to ${{ github.base_ref }}
        --retry-while-unknown 0 
        --retry-interval 10
        --broker-base-url ${{ inputs.PACT_BROKER_BASE_URL }}
        --broker-token ${{ inputs.PACT_BROKER_TOKEN }}
      shell: bash
