name: contract-test-dev

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}
  PACTICIPANT: person-consumer
  APP_ENVIRONMENT: dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Setup pact-cli
        run: docker pull pactfoundation/pact-cli:latest
      - name: Publish Pact
        run: >
          docker run --rm  -v $PWD:$PWD pactfoundation/pact-cli:latest
          publish $PWD/pacts 
          --consumer-app-version ${{ github.sha }} 
          --tag ${APP_ENVIRONMENT}
          --broker-base-url $PACT_BROKER_BASE_URL
          --broker-token $PACT_BROKER_TOKEN

  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup pact-cli
        run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: >
          docker run pactfoundation/pact-cli:latest
          broker can-i-deploy
          --pacticipant $PACTICIPANT 
          --version ${{ github.sha }}
          --to $APP_ENVIRONMENT
          --retry-while-unknown 0 
          --retry-interval 10
          --broker-base-url $PACT_BROKER_BASE_URL
          --broker-token $PACT_BROKER_TOKEN
