name: tag-contract

on:
  pull_request:
    types:
      - closed

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}

jobs:
  tag-contract:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: >
          yarn pact-broker create-version-tag 
          --pacticipant person-consumer
          --version ${{ github.event.pull_request.head.sha }}
          --tag dev
          --broker-base-url $PACT_BROKER_BASE_URL 
          --broker-token $PACT_BROKER_TOKEN
